version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: delivery-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: delivery-web
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/deliverydb?schema=public
      - WATCHPACK_POLLING=true
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db

volumes:
  pgdata:
